### ISSUE TITLE
cannot import name parse_http_list

### ISSUE THREAD

**Issue by davidbono** [LukeMurphey/splunk-web-input#8]
Hello,

Since Splunk 8.0, all webscrapping failed with error :" cannot import name parse_http_list"

```
   Traceback (most recent call last):
     File "/opt/splunk/etc/apps/website_input/bin/web_scrape.py", line 9, in <module>
       from website_input_app.search_command import SearchCommand
     File "/opt/splunk/etc/apps/website_input/bin/website_input_app/search_command.py", line 31, in <module>
       from splunk.appserver.mrsparkle.lib.util import make_splunkhome_path
     File "/opt/splunk/lib/python2.7/site-packages/splunk/appserver/mrsparkle/lib/util.py", line 22, in <module>
       import cherrypy
     File "/opt/splunk/lib/python2.7/site-packages/cherrypy/__init__.py", line 73, in <module>
       from ._cptools import default_toolbox as tools, Tool
     File "/opt/splunk/lib/python2.7/site-packages/cherrypy/_cptools.py", line 33, in <module>
       from cherrypy.lib import auth_basic, auth_digest
     File "/opt/splunk/lib/python2.7/site-packages/cherrypy/lib/auth_digest.py", line 27, in <module>
       from six.moves.urllib.request import parse_http_list, parse_keqv_list
   ImportError: cannot import name parse_http_list
10-30-2019 14:46:02.223 ERROR script - sid:1572446761.370 External search command 'webscrape' returned error code 1. .
```

**Comment by LukeMurphey** [comment]
I'll check this out. I haven't tested this app in Splunk 8.0 yet. I know that I need to make at least one change to make the app work on 8.0.

**Comment by davidbono** [comment]
Allright, let me know if you want me to help in testing.

**Comment by LukeMurphey** [comment]
FYI: I have the conversion to Splunk 8.0 and Python 2 + 3 in progress. Should be done within the next few days.

**Comment by davidbono** [comment]
Hello,
Since the last update from splunkbase.com, everything goes well.
Well done and thanks a lot.

**Comment by LukeMurphey** [comment]
Oops, sorry for not letting you know I published an update.
